---

version: '3.9'

services:
  api:
    image: ${IMAGE_TAG}
    deploy:
      mode: replicated
      replicas: ${REPLICAS}
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 2
        delay: 15s
        order: start-first
    environment:
      # No CRON
      ACCOUNTS_QUEUE_URL: ${ACCOUNTS_QUEUE_URL}
      ACCOUNT_SID: ${ACCOUNT_SID}
      ACCOUNT_TOKEN: ${ACCOUNT_TOKEN}
      ALEMBIC_INI_FILE: 'alembic.ini'
      ALGORITHM: 'HS256'
      AWS_REGION: 'us-west-1'
      BASE_URL: 'https://milestones-${ENV}.blueboard.app'
      ENV: ${ENV}
      FERNET_KEY: ${FERNET_KEY}
      JWT_ENFORCED: 'true' # TODO this is temporary
      LOG_LEVEL: debug
      MOCK: 'False'
      POSTGRES_DB: milestones_${ENV}
      POSTGRES_HOSTNAME: ${POSTGRES_HOSTNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      RAILS_API: ${RAILS_API}
      RAILS_JWT_SECRET_KEY: ${RAILS_JWT_SECRET_KEY}
      SECRET_KEY: ${SECRET_KEY}
      SEGMENT_QUERY_QUEUE_URL: ${SEGMENT_QUERY_QUEUE_URL}
      SEGMENT_RESPONSE_QUEUE_URL: ${SEGMENT_RESPONSE_QUEUE_URL}
      REWARDS_QUEUE_URL: ${REWARDS_QUEUE_URL}
      SPARKPOST_KEY: ${SPARKPOST_KEY}
      TWILIO_FROM: '+16193299600'
      YASS_URL: 'http://yass_api/v1'
    networks:
      - blueboard_${ENV}
    ports:
      - 8080:80
    entrypoint: /entrypoint.sh
  worker:
    image: ${IMAGE_TAG}
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 15s
        order: start-first
    environment:
      CRON: 'true' # must be a string, not a boolean
      # Most of these env vars are not needed by the worker instance per say, but are required by the app to start/run
      # this list is copied from above
      ACCOUNTS_QUEUE_URL: ${ACCOUNTS_QUEUE_URL}
      ACCOUNT_SID: ${ACCOUNT_SID}
      ACCOUNT_TOKEN: ${ACCOUNT_TOKEN}
      ALEMBIC_INI_FILE: 'alembic.ini'
      ALGORITHM: 'HS256'
      AWS_REGION: 'us-west-1'
      BASE_URL: 'https://milestones-${ENV}.blueboard.app'
      ENV: ${ENV}
      FERNET_KEY: ${FERNET_KEY}
      JWT_ENFORCED: 'true' # TODO this is temporary
      LOG_LEVEL: debug
      MOCK: 'False'
      POSTGRES_DB: milestones_${ENV}
      POSTGRES_HOSTNAME: ${POSTGRES_HOSTNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      RAILS_API: ${RAILS_API}
      RAILS_JWT_SECRET_KEY: ${RAILS_JWT_SECRET_KEY}
      SECRET_KEY: ${SECRET_KEY}
      SEGMENT_QUERY_QUEUE_URL: ${SEGMENT_QUERY_QUEUE_URL}
      SEGMENT_RESPONSE_QUEUE_URL: ${SEGMENT_RESPONSE_QUEUE_URL}
      SPARKPOST_KEY: ${SPARKPOST_KEY}
      TWILIO_FROM: '+16193299600'
      YASS_URL: 'http://yass_api/v1'
    networks:
      - blueboard_${ENV}
    entrypoint: /entrypoint.sh

networks:
  blueboard_${ENV}:
    external: true
