---

version: '3.9'

services:
  api:
    image: ${IMAGE_TAG}
    deploy:
      mode: replicated
      replicas: ${REPLICAS}
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 2
        delay: 15s
        order: start-first
    environment:
      ACCOUNT_SID: ${ACCOUNT_SID}
      ACCOUNT_TOKEN: ${ACCOUNT_TOKEN}
      ALEMBIC_INI_FILE: 'alembic.ini'
      ALGORITHM: 'HS256'
      BASE_URL: 'https://milestones-${ENV}.blueboard.app'
      # No CRON
      ENV: ${ENV}
      FERNET_KEY: ${FERNET_KEY}
      JOB_QUEUE_HOST: ${JOB_QUEUE_HOST}
      JOB_QUEUE_PORT: 11300
      JOB_QUEUE_TUBE: 'milestones_tube'
      JWT_ENFORCED: 'False' # TODO this is temporary
      LOG_LEVEL: debug
      POSTGRES_DB: blueboard_milestones
      POSTGRES_HOSTNAME: ${POSTGRES_HOSTNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      RAILS_API: ${RAILS_API}
      RAILS_JWT_SECRET_KEY: ${RAILS_JWT_SECRET_KEY}
      SECRET_KEY: ${SECRET_KEY}
      SPARKPOST_KEY: ${SPARKPOST_KEY}
      TWILIO_FROM: '+16193299600'
      YASS_URL: 'http://yass_api/v1'
    networks:
      - blueboard_${ENV}
    ports:
      - 8080:80
    entrypoint: /entrypoint.sh # this  is renamed from the swarm entrpoint script
  worker:
    image: ${IMAGE_TAG}
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 15s
        order: start-first
    environment:
      # Most of these env vars are not needed by the worker instance per say, but are required by the app to start/run
      ACCOUNT_SID: ${ACCOUNT_SID}
      ACCOUNT_TOKEN: ${ACCOUNT_TOKEN}
      ALEMBIC_INI_FILE: 'alembic.ini'
      ALGORITHM: 'HS256'
      BASE_URL: 'https://milestones-${ENV}.blueboard.app'
      CRON: 'true'
      ENV: ${ENV}
      FERNET_KEY: ${FERNET_KEY}
      JOB_QUEUE_HOST: ${JOB_QUEUE_HOST}
      JOB_QUEUE_PORT: 11300
      JOB_QUEUE_TUBE: 'milestones_tube'
      JWT_ENFORCED: 'False' # TODO this is temporary
      LOG_LEVEL: debug
      POSTGRES_DB: blueboard_milestones
      POSTGRES_HOSTNAME: ${POSTGRES_HOSTNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      RAILS_API: ${RAILS_API}
      RAILS_JWT_SECRET_KEY: ${RAILS_JWT_SECRET_KEY}
      SECRET_KEY: ${SECRET_KEY}
      SPARKPOST_KEY: ${SPARKPOST_KEY}
      TWILIO_FROM: '+16193299600'
      YASS_URL: 'http://yass_api/v1'
    networks:
      - blueboard_${ENV}
    entrypoint: /entrypoint.sh # this is renamed from the swarm entrpoint script

networks:
  blueboard_${ENV}:
    external: true
