# more stripped down Dockerfile for the Milestones API
FROM python:3.11
WORKDIR /app

RUN apt-get update
RUN apt -y install iputils-ping lsof vim
RUN apt -y install default-mysql-client python3-pymysql alembic

# install dependencies first so that changes in application code do not invalidate
# the cache of the layer with installed dependencies
COPY requirements.txt ./
# when pip install is here, docker caches all the pip dependencies
RUN pip install -r requirements.txt
# copy the application and tests
COPY app/ /app/app
COPY tests/ /app/tests

# run the app
CMD ["uvicorn", "app.main:app", "--proxy-headers", "--host", "0.0.0.0", "--port", "80"]