#
# Use with a .env file like:
# TAG=latest
#
# test with: docker compose config
#
#
# docker-compose --file docker-compose-dev.yml up --build
#
version: '3'
services:
  milestones_db:
    container_name: milestones_db
    hostname: milestones_db
    image:  mariadb:latest
    volumes:
      - '/opt/mariadb-data/:/var/lib/mysql'
    environment:
      # server settings
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
      MYSQL_LOG_CONSOLE: true
      # bootstrap a db and db user
      MYSQL_DATABASE: blueboard_milestones
      MYSQL_USER: milestones
      MYSQL_PASSWORD: milestones
    ports:
      - 3306:3306 # probably don't need this
    restart: always
  milestones_api:
    container_name: milestones_api
    image:  "blueboardinc/milestones-api:${TAG}"
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      DD_AGENT_HOST: datadog_agent
      DD_PROFILING_ENABLED: true
      BEARER_TOKEN: ${BEARER_TOKEN}
      LOG_LEVEL: debug
      # connection settings for the app, these should match server's config (above)
      MYSQL_DATABASE: blueboard_milestones
      MYSQL_USER: milestones
      MYSQL_PASSWORD: milestones
      MYSQL_HOSTNAME: milestones_db # this is basically container name (above)
      MYSQL_PORT: 3306
      MILESTONES_BOOTSTRAP: "migrations/milestones_nodata_v1.4.1.sql"
    ports:
      - 8080:80 # probably don't need this
    depends_on:
      - milestones_db
    # entrypoint: /start.sh
    restart: always
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile.nginx
      args:
        - DOCS_USERNAME=milestones
        - DOCS_PASSWORD=${DOCS_PASSWORD}
    image: custom-nginx-proxy:latest # custom name
    ports:
      - 80:80 # host:container
    restart: always
  datadog_agent:
    container_name: datadog_agent
    build:
      context: .
      dockerfile: Dockerfile.datadog
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    environment:
      DD_APM_ENABLED: true
      DD_APM_NON_LOCAL_TRAFFIC: true
      DD_LOGS_ENABLED: true
      DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL: true
      DD_SERVICE: "milestones-api"
      DD_ENV: "dev"
      DD_API_KEY: ${DD_API_KEY}
      DD_CONTAINER_INCLUDE: "name:milestones_api"
      DD_CONTAINER_EXCLUDE: "name:milestones_db name:datadog name:nginx" 
    restart: always
  