# This is the Docker stack file that describes the Milestones application
#
# Do a Docker login then:
# docker stack deploy --compose-file docker-swarm.yml --with-registry-auth milestones
#
# Compose file deploy reference:
# https://docs.docker.com/compose/compose-file/deploy/
#
# Note that Docker stacks do not support .env files  :-(
#
# If you omit the mode key or set it to ingress, the routing mesh is used.
# https://docs.docker.com/engine/swarm/ingress/
#
version: "3.9"
services:
  api:
    image:  blueboardinc/milestones-api:v0.0.7-54477d3
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 2
        delay: 15s
        order: start-first
      # resources:
      #   limits:
      #     cpus: '0.5'
      #     memory: 350M
      #   reservations:
      #     cpus: '0.1'
      #     memory: 100M
    environment:
      ACCOUNT_SID: "1234"
      ACCOUNT_TOKEN: "1234"
      ALEMBIC_INI_FILE: "alembic.ini"
      ALGORITHM: "HS256"
      AWS_ACCESS_KEY_ID: "1234"
      AWS_SECRET_ACCESS_KEY: "1234"
      # Datadog is fully disabled
      DATADOG_TRACE_ENABLED: 0
      ENV: dev
      LOG_LEVEL: debug
      MILESTONES_BOOTSTRAP: "migrations/milestones_nodata_v1.9.2.sql"
      # connection settings for the app, these should match server"s config (above)
      MYSQL_DATABASE: blueboard_milestones
      MYSQL_HOSTNAME: milestones_db # this is basically container name (above)
      MYSQL_PASSWORD: milestones # see comment above
      MYSQL_PORT: 3306
      MYSQL_USER: milestones
      SECRET_KEY: "6973dddb2cc93b7ab931fb707292ae7dc9a763db1ef73707047bb747b2b8851c"
      SPARKPOST_KEY: "1234"
      TWILIO_FROM: "1234"
    ports:
      - 8080:80
    entrypoint: /entrypoint.sh # this is renamed entrypoint_hosted.sh
  nginx:
    image:  blueboardinc/milestones-nginx:latest
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - 80:80
  db:
    image: mariadb:latest
    deploy:
      mode: replicated
      replicas: 1
    # volumes:
    #   - './mariadb-data/:/var/lib/mysql'
    environment:
      # server settings
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: "%"
      MYSQL_LOG_CONSOLE: "true"
      # bootstrap a db and db user
      MYSQL_DATABASE: blueboard_milestones
      MYSQL_USER: milestones
      MYSQL_PASSWORD: milestones
    ports:
      - 3306:3306
  # beanstalkd:
  #   image: schickling/beanstalkd
  #   replicas: 1
  #   ports:
  #     - 11300:11300
