version: '3'
name: milestones_api
services:
  milestones_db:
    extends:
      file: docker-compose.yml
      service: milestones_db
  milestones_api:
    extends:
      file: docker-compose.yml
      service: milestones_api
    environment:
      DEBUG: 'True'
      LOG_LEVEL: debug
    ports:
      - '80:80'
      - '5677:5677'
    entrypoint: /entrypoint.sh

networks:
  auth_network:
      driver: bridge
      name: auth_network
      external: true
