---

name: Recycle Containers ♻️

description: Copies YAML file to Swarm nodes and tells Docker Swarm to re-start containers

inputs:
  hosts:
    description: 'List of all hosts to copy the YAML file to'
    required: true
  leader:
    description: 'The leader of the Swarm node'
    required: true
  username:
    description: 'The usename for the ssh copy'
    default: 'blueboard'
    required: false
  key_path:
    description: 'Path to the ssh key for ssh/scp'
    default:  ${{ github.workspace }}/.ssh/id_ecdsa
    required: false
  dockerhub_username:
    description: 'Read only user to authenticate with Docker Hub to pull private containers'
    required: true
  dockerhub_password:
    description: 'Read only user to authenticate with Docker Hub to pull private containers'
    required: true
  app:
    description: 'This is the argument passed to the run.sh script'
    required: true
  yaml_file:
    description: 'The YAML file to copy'
    required: true

runs:
  using: "composite"
  steps:
    - name: Copy the YAML file to all Docker Swarm nodes
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ inputs.hosts }}
        port: 22
        username: ${{ inputs.username }}
        key_path: ${{ inputs.key_path }}
        source: ${{ inputs.yaml_file }}
        target: /home/blueboard

    - name: Pull image and update Docker Swarm
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ inputs.leader }}
        port: 22
        username: ${{ inputs.username }}
        key_path: ${{ inputs.key_path }}
        script: |
          cd /home/blueboard
          ./run.sh ${{ inputs.dockerhub_username }} ${{ inputs.dockerhub_password }} ${{ inputs.app }} > ${{ inputs.app }}.log