# This is a more stripped down Dockerfile for the Milestones API
FROM python:3.11.3
WORKDIR /app

RUN apt-get update
RUN apt -y install iputils-ping vim 
RUN apt -y install default-mysql-client python3-pymysql alembic
RUN apt -y install cron
# DataDog
RUN pip install ddtrace
# install dependencies first so that changes in application code do not invalidate
# the cache of the layer with installed dependencies
COPY requirements.txt ./
# when pip install is here, docker caches all the pip dependencies
RUN pip install -r requirements.txt
# copy the application
COPY app/ /app/app
COPY ./migrations /app/migrations
COPY alembic.ini /app
COPY Docker/crontab /crontab
COPY Docker/entrypoint_hosted.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh