FROM python:3.11.4-slim-bullseye
WORKDIR /app

RUN apt-get update \
  && apt -y install iputils-ping vim postgresql-client alembic cron curl dnsutils \
  && apt-get clean

# DataDog
RUN pip install ddtrace

COPY requirements.txt ./
RUN pip install -r requirements.txt

# copy the application
COPY app/ /app/app
COPY burp/ /app/burp
COPY ./migrations /app/migrations
COPY alembic.ini /app

COPY Docker/entrypoint_swarm.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

COPY Docker/localstack_ip.sh /localstack_ip.sh
RUN chmod +x /localstack_ip.sh