# to build and use this on the dev Docker Swarm environment, follow the instruct
# docker build \
#   --platform linux/amd64 \
#   --file Docker/Dockerfile.localstack_localhost \
#   --tag blueboardinc/localstack:latest .

# docker push docker push blueboardinc/localstack:latest

FROM localstack/localstack:latest
COPY Docker/localstack_ready.sh /etc/localstack/init/ready.d/ready.sh
RUN chmod +x /etc/localstack/init/ready.d/ready.sh
