"""add staged_reward table

Revision ID: 2f4a4f2c7a8d
Revises: ab5d4100e395
Create Date: 2024-01-18 17:10:02.187613-08:00

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '2f4a4f2c7a8d'
down_revision = 'ab5d4100e395'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staged_reward',
    sa.Column('uuid', sa.String(length=56), nullable=False),
    sa.Column('reward_id', sa.Integer(), nullable=True),
    sa.Column('user_account_uuid', sa.String(length=65), nullable=False),
    sa.Column('rule_uuid', sa.String(length=56), nullable=False),
    sa.Column('send_on', sa.String(length=56), nullable=False),
    sa.Column('send_at', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=56), nullable=False),
    sa.Column('approved_at', sa.String(length=56), nullable=True),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('employee_account_id', sa.Integer(), nullable=False),
    sa.Column('gid', sa.String(length=56), nullable=False),
    sa.Column('first_name', sa.String(length=56), nullable=False),
    sa.Column('last_name', sa.String(length=56), nullable=False),
    sa.Column('email', sa.String(length=56), nullable=False),
    sa.Column('time_created', sa.Integer(), nullable=True),
    sa.Column('time_updated', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_staged_reward_company_id'), 'staged_reward', ['company_id'], unique=False)
    op.create_index(op.f('ix_staged_reward_program_id'), 'staged_reward', ['program_id'], unique=False)
    op.create_index(op.f('ix_staged_reward_rule_uuid'), 'staged_reward', ['rule_uuid'], unique=False)
    op.create_index(op.f('ix_staged_reward_send_on'), 'staged_reward', ['send_on'], unique=False)
    op.create_index(op.f('ix_staged_reward_send_at'), 'staged_reward', ['send_at'], unique=False)
    op.create_index(op.f('ix_staged_reward_state'), 'staged_reward', ['state'], unique=False)
    op.create_index(op.f('ix_staged_reward_user_account_uuid'), 'staged_reward', ['user_account_uuid'], unique=False)
    op.create_index(op.f('ix_staged_reward_reward_id'), 'staged_reward', ['reward_id'], unique=False)
    op.create_index(op.f('ix_staged_reward_uuid'), 'staged_reward', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staged_reward_uuid'), table_name='staged_reward')
    op.drop_index(op.f('ix_staged_reward_reward_id'), table_name='staged_reward')
    op.drop_index(op.f('ix_staged_reward_user_account_uuid'), table_name='staged_reward')
    op.drop_index(op.f('ix_staged_reward_state'), table_name='staged_reward')
    op.drop_index(op.f('ix_staged_reward_send_at'), table_name='staged_reward')
    op.drop_index(op.f('ix_staged_reward_send_on'), table_name='staged_reward')
    op.drop_index(op.f('ix_staged_reward_rule_uuid'), table_name='staged_reward')
    op.drop_index(op.f('ix_staged_reward_program_id'), table_name='staged_reward')
    op.drop_index(op.f('ix_staged_reward_company_id'), table_name='staged_reward')
    op.drop_table('staged_reward')
    # ### end Alembic commands ###
