"""base migration

Revision ID: aa7f167f7d42
Revises: 
Create Date: 2024-02-28 10:27:59.402142-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa7f167f7d42'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rule',
    sa.Column('uuid', sa.String(length=56), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('rule_name', sa.String(length=255), nullable=False),
    sa.Column('rule_type', sa.String(length=56), nullable=False),
    sa.Column('trigger_field', sa.String(length=56), nullable=False),
    sa.Column('timing_type', sa.String(length=56), nullable=False),
    sa.Column('days_prior', sa.Integer(), nullable=True),
    sa.Column('sending_time', sa.String(length=56), nullable=False),
    sa.Column('timezone', sa.JSON(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('sending_managers_account_id', sa.Integer(), nullable=False),
    sa.Column('sending_managers_program_id', sa.Integer(), nullable=False),
    sa.Column('bucket_customization_id', sa.Integer(), nullable=False),
    sa.Column('bucket_customization_price', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('memo', sa.String(length=255), nullable=False),
    sa.Column('recipient_note', sa.String(length=255), nullable=False),
    sa.Column('company_values', sa.JSON(), nullable=False),
    sa.Column('segmented_by', sa.JSON(), nullable=True),
    sa.Column('anniversary_years', sa.JSON(), nullable=True),
    sa.Column('onboarding_period', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=56), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('time_created', sa.Integer(), nullable=True),
    sa.Column('time_updated', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_rule_company_id'), 'rule', ['company_id'], unique=False)
    op.create_index(op.f('ix_rule_manager_id'), 'rule', ['manager_id'], unique=False)
    op.create_index(op.f('ix_rule_rule_name'), 'rule', ['rule_name'], unique=False)
    op.create_index(op.f('ix_rule_rule_type'), 'rule', ['rule_type'], unique=False)
    op.create_index(op.f('ix_rule_sending_managers_program_id'), 'rule', ['sending_managers_program_id'], unique=False)
    op.create_index(op.f('ix_rule_sending_time'), 'rule', ['sending_time'], unique=False)
    op.create_index(op.f('ix_rule_state'), 'rule', ['state'], unique=False)
    op.create_index(op.f('ix_rule_timing_type'), 'rule', ['timing_type'], unique=False)
    op.create_index(op.f('ix_rule_trigger_field'), 'rule', ['trigger_field'], unique=False)
    op.create_index(op.f('ix_rule_uuid'), 'rule', ['uuid'], unique=False)
    op.create_table('staged_reward',
    sa.Column('uuid', sa.String(length=56), nullable=False),
    sa.Column('reward_id', sa.Integer(), nullable=True),
    sa.Column('user_account_uuid', sa.String(length=65), nullable=False),
    sa.Column('rule_uuid', sa.String(length=56), nullable=False),
    sa.Column('send_on', sa.DateTime(), nullable=True),
    sa.Column('send_at', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=56), nullable=False),
    sa.Column('approved_at', sa.String(length=56), nullable=True),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('employee_account_id', sa.Integer(), nullable=False),
    sa.Column('gid', sa.String(length=56), nullable=False),
    sa.Column('bucket_customization_id', sa.Integer(), nullable=False),
    sa.Column('bucket_customization_price', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('time_created', sa.Integer(), nullable=True),
    sa.Column('time_updated', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_staged_reward_company_id'), 'staged_reward', ['company_id'], unique=False)
    op.create_index(op.f('ix_staged_reward_full_name'), 'staged_reward', ['full_name'], unique=False)
    op.create_index(op.f('ix_staged_reward_program_id'), 'staged_reward', ['program_id'], unique=False)
    op.create_index(op.f('ix_staged_reward_reward_id'), 'staged_reward', ['reward_id'], unique=False)
    op.create_index(op.f('ix_staged_reward_rule_uuid'), 'staged_reward', ['rule_uuid'], unique=False)
    op.create_index(op.f('ix_staged_reward_send_at'), 'staged_reward', ['send_at'], unique=False)
    op.create_index(op.f('ix_staged_reward_send_on'), 'staged_reward', ['send_on'], unique=False)
    op.create_index(op.f('ix_staged_reward_state'), 'staged_reward', ['state'], unique=False)
    op.create_index(op.f('ix_staged_reward_user_account_uuid'), 'staged_reward', ['user_account_uuid'], unique=False)
    op.create_index(op.f('ix_staged_reward_uuid'), 'staged_reward', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staged_reward_uuid'), table_name='staged_reward')
    op.drop_index(op.f('ix_staged_reward_user_account_uuid'), table_name='staged_reward')
    op.drop_index(op.f('ix_staged_reward_state'), table_name='staged_reward')
    op.drop_index(op.f('ix_staged_reward_send_on'), table_name='staged_reward')
    op.drop_index(op.f('ix_staged_reward_send_at'), table_name='staged_reward')
    op.drop_index(op.f('ix_staged_reward_rule_uuid'), table_name='staged_reward')
    op.drop_index(op.f('ix_staged_reward_reward_id'), table_name='staged_reward')
    op.drop_index(op.f('ix_staged_reward_program_id'), table_name='staged_reward')
    op.drop_index(op.f('ix_staged_reward_full_name'), table_name='staged_reward')
    op.drop_index(op.f('ix_staged_reward_company_id'), table_name='staged_reward')
    op.drop_table('staged_reward')
    op.drop_index(op.f('ix_rule_uuid'), table_name='rule')
    op.drop_index(op.f('ix_rule_trigger_field'), table_name='rule')
    op.drop_index(op.f('ix_rule_timing_type'), table_name='rule')
    op.drop_index(op.f('ix_rule_state'), table_name='rule')
    op.drop_index(op.f('ix_rule_sending_time'), table_name='rule')
    op.drop_index(op.f('ix_rule_sending_managers_program_id'), table_name='rule')
    op.drop_index(op.f('ix_rule_rule_type'), table_name='rule')
    op.drop_index(op.f('ix_rule_rule_name'), table_name='rule')
    op.drop_index(op.f('ix_rule_manager_id'), table_name='rule')
    op.drop_index(op.f('ix_rule_company_id'), table_name='rule')
    op.drop_table('rule')
    # ### end Alembic commands ###
