"""adds segment_rule table

Revision ID: d21c5559ec91
Revises: 04a533a9ac68
Create Date: 2024-01-23 17:28:44.153678-08:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd21c5559ec91'
down_revision = '04a533a9ac68'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('segment_rule',
    sa.Column('uuid', sa.String(length=56), nullable=False),
    sa.Column('parent_rule', sa.String(length=56), nullable=False),
    sa.Column('segmented_by', sa.JSON(), nullable=False),
    sa.Column('bucket_customization_id', mysql.INTEGER(), nullable=False),
    sa.Column('created_by', mysql.INTEGER(), nullable=False),
    sa.Column('updated_by', mysql.INTEGER(), nullable=False),
    sa.Column('time_created', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column('time_updated', mysql.INTEGER(display_width=11), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_segment_rule_bucket_customization_id'), 'segment_rule', ['bucket_customization_id'], unique=False)
    op.create_index(op.f('ix_segment_rule_parent_rule'), 'segment_rule', ['parent_rule'], unique=False)
    op.create_index(op.f('ix_segment_rule_uuid'), 'segment_rule', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_segment_rule_uuid'), table_name='segment_rule')
    op.drop_index(op.f('ix_segment_rule_parent_rule'), table_name='segment_rule')
    op.drop_index(op.f('ix_segment_rule_bucket_customization_id'), table_name='segment_rule')
    op.drop_table('segment_rule')
    # ### end Alembic commands ###
