"""adds reward table

Revision ID: a170534ed314
Revises: 1ce40a8b8fe4
Create Date: 2023-12-06 14:46:22.651062

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a170534ed314'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reward',
    sa.Column('uuid', sa.String(length=56), nullable=False),
    sa.Column('client_admin_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('rule', sa.JSON(), nullable=False),
    sa.Column('users', sa.JSON(), nullable=False),
    sa.Column('reward_info', sa.JSON(), nullable=False),
    sa.Column('time_created', sa.Integer(), nullable=True),
    sa.Column('time_updated', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_reward_client_admin_id'), 'reward', ['client_admin_id'], unique=False)
    op.create_index(op.f('ix_reward_company_id'), 'reward', ['company_id'], unique=False)
    op.create_index(op.f('ix_reward_uuid'), 'reward', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reward_uuid'), table_name='reward')
    op.drop_index(op.f('ix_reward_company_id'), table_name='reward')
    op.drop_index(op.f('ix_reward_client_admin_id'), table_name='reward')
    op.drop_table('reward')
    # ### end Alembic commands ###
