#
# This config is deprecated -- currently used only in the single AWS instance
#
FROM nginx:latest
# args we're passing into Docker from the command line
ARG DOCS_USERNAME
ARG DOCS_PASSWORD

RUN rm -f /etc/nginx/conf.d/default.conf
COPY milestones-nginx.conf /etc/nginx/conf.d/milestones.conf

RUN apt update
RUN apt install -y apache2-utils iputils-ping vim procps

# use basic .htaccess to password-protect the /docs route
RUN echo "the .htaccess username is ${DOCS_USERNAME}"
RUN htpasswd -cb /opt/milestones.htpasswd ${DOCS_USERNAME} ${DOCS_PASSWORD}