name: Build Docker Image

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-*'

jobs:
  run-postman-tests:
    name: Run Postman Tests
    runs-on: ubuntu-latest
    env:
        DD_API_KEY: "foobar"
        DD_APP_KEY: "foobar"
        ACCOUNT_SID: "foobar"
        ACCOUNT_TOKEN: "foobar"
        ALGORITHM: "HS256"
        AWS_ACCESS_KEY_ID: "foobar"
        AWS_SECRET_ACCESS_KEY: "foobar"
        ENV: "local"
        FERNET_KEY: "foooooooooooooooooobarrrrrrrrrrrrrrrrrrrrrr="
        SECRET_KEY: "foobar"
        SPARKPOST_KEY: "foobar"
        TWILIO_FROM: "+16193299600"
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Start Docker containers
        # because this is detached, if the app crashes on startup (due to, for example, a missing env var)
        # the failure is not apparant on Github -- validate this on localhost using a .env file with the vars
        # above
        run: |
          docker-compose up --build --detach

      - name: Pause to let app to fully start
        # this may be problematic in the future
        run: |
          sleep 30

      - name: Run Postman tests
        run: |
          docker exec --tty milestones_api /app/tests/postman.sh

      - name: Stop Docker containers
        if: always()
        run: |
          docker-compose down

      - name: Echo job status
        if: always()
        run: |
          echo "Job status is ${{ job.status }}"

      - name: Update Github with job status
        if: always()
        uses: ouzi-dev/commit-status-updater@v2
        with:
          name: "Postman test results"
          status: ${{ job.status }}

  build-api:
    name: Build API
    needs: run-postman-tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN_RW }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: blueboardinc/milestones-api

      - name: Build, tag and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Docker/Dockerfile.milestones_api_hosted
          push: true
          cache-from: type=registry,ref=blueboardinc/milestones-api:latest
          cache-to: type=inline
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

