name: Build Docker Image

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-*'

jobs:
  build-api:
    name: Build API
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN_RW }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: blueboardinc/milestones-api

      - name: Build, tag and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Docker/Dockerfile.milestones_api_hosted
          push: true
          cache-from: type=registry,ref=blueboardinc/milestones-api:latest
          cache-to: type=inline
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  run-postman-tests:
    name: Run Postman test suite
    runs-on: ubuntu-latest
    env:
        DD_API_KEY: "foobar"
        DD_APP_KEY: "foobar"
        ACCOUNT_SID: "foobar"
        ACCOUNT_TOKEN: "foobar"
        ALGORITHM: "HS256"
        AWS_ACCESS_KEY_ID: "foobar"
        AWS_SECRET_ACCESS_KEY: "foobar"
        SECRET_KEY: "foobar"
        SPARKPOST_KEY: "foobar"
        TWILIO_FROM: "+16193299600"

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Start Docker containers
        run: |
          docker-compose up --build --detach

      - name: Pause to let app to start
        run: |
          sleep 30

      - name: Run Postman tests
        run: |
          docker exec --tty milestones_api /app/tests/postman.sh

      - name: Stop Docker containers
        if: always()
        run: |
          docker-compose down

      - name: Test
        if: always()
        run: |
          echo "job status is ${{ job.status }}"

      - name: Update Github status
        if: always()
        uses: ouzi-dev/commit-status-updater@v2
        with:
          name: "Postman test results"
          status: ${{ job.status }}