name: Deploy

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'What tag?'
        required: true
      environment:
        description: 'To which environment?'
        type: choice
        default: 'staging'
        options:
          - staging
          - production
jobs:
  deploy:
    name: Deploy to environment
    runs-on: ubuntu-latest
    steps:
      
      - name: Log in to Docker Hub with PAT
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Deploy release
        run: |
          echo 'Deploy version with tag ${{ github.event.inputs.tag }} to ${{ github.event.inputs.environment }}'
