name: Deploy to Docker Swarm

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Which Docker image tag?'
        required: true
        default: 'latest'
      environment:
        description: 'To what environment?'
        type: choice
        default: 'dev'
        options:
          - dev
          - staging
      ref:
        description: 'Branch with Docker Swarm YAML template?'
        default: 'staging'

env:
  SWARM_YAML: "docker-milestones-api-swarm.yml"

jobs:
  deploy:
    name: Deploy ${{ github.event.inputs.tag }} to ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.ref }}
          fetch-depth: 1

      - name: Install OpenVPN
        run: |
          sudo apt-get update
          sudo apt-get --assume-yes --no-install-recommends install openvpn

      - name: Setup VPN config using organization secrets
        # these values are from the OpenVPN config and defined as Organization secrets in GitHub
        # secret.txt is in the form of usename and password, each on its own line
        run: |
          echo "${{ secrets.DEV_VPN_CA_CRT }}" > ca.crt
          echo "${{ secrets.DEV_VPN_CERT_CRT }}" > user.crt
          echo "${{ secrets.DEV_VPN_CERT_KEY }}" > user.key && chmod 400 user.key
          echo "${{ secrets.DEV_VPN_SECRET_USERNAME_PASSWORD }}" > secret.txt && chmod 400 secret.txt
          echo "${{ secrets.DEV_VPN_TLS_KEY }}" > tls.key

      - name: Connect VPN
        run: sudo openvpn --config ".github/vpn/config.ovpn" --log "vpn.log" --daemon

      - name: Wait for the VPN connection
        timeout-minutes: 1
        run: |
          until ping -c1 ${{ github.event.inputs.environment == 'staging' && secrets.STAGING_LEADER || secrets.DEV_LEADER }}; do sleep 2; done

      - name: Export all GitHub secrets as environment variables
        env:
          SECRETS: ${{ toJson(secrets) }}
        run: |
          # the purpose of this step is to export all GitHub secrets as regular
          # env vars so that we can use envsubst in a subsequent step
          # Note: jq adds double quotes around the value, so we must use sed to
          # re-wrap the values with single quotes, but still allowing for double
          # quotes in the env var itself, i.e. so that we end up with this:
          #
          # foo='foobar'
          # bar='barfoo'
          # foobar='bar"foo"foo'
          #
          echo $SECRETS | jq --raw-output '. | to_entries[] | .key + "=" + (.value | tojson)' | \
            sed "s/\=\"/\=\'/" | \
            sed "s/\"$/'/" | \
            sed "s/\"$/'/" >> $GITHUB_ENV
          unset SECRETS

      - name: Prepare the Docker Swarm YAML file
        env:
          ENV: ${{ github.event.inputs.environment }}                   # workflow variable
          IMAGE_TAG: ${{ github.event.inputs.tag }}                     # workflow variable
        run: |
          # append the tag to form a fully qualified Docker tag
          export IMAGE_TAG=blueboardinc/milestones-api:${IMAGE_TAG}
          YAML_COMMENT="\n#\n# This YAML config was auto-generated by a Github Action on $(date)\n#\n"
          mv ${SWARM_YAML} ${SWARM_YAML}.orig
          # the use of sed here is a primitive brute-force attempt to squash any double-single quotes
          envsubst < ${SWARM_YAML}.orig | sed s/\'\'/\'/g > ${SWARM_YAML}
          echo -en ${YAML_COMMENT} >> ${SWARM_YAML}

      - name: Copy the YAML file to all Docker Swarm nodes
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ github.event.inputs.environment == 'staging' && secrets.STAGING_HOSTS || secrets.DEV_HOSTS }}
          port: 22
          username: blueboard
          key: ${{ github.event.inputs.environment == 'staging' && secrets.STAGING_SSH_KEY || secrets.DEV_SSH_KEY }}
          source: ${{ env.SWARM_YAML }}
          target: /home/blueboard

      - name: Pull image and update Docker Swarm
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ github.event.inputs.environment == 'staging' && secrets.STAGING_LEADER || secrets.DEV_LEADER }}
          port: 22
          username: blueboard
          key: ${{ github.event.inputs.environment == 'staging' && secrets.STAGING_SSH_KEY || secrets.DEV_SSH_KEY }}
          script: |
            cd /home/blueboard
            ./run.sh ${{ secrets.DOCKERHUB_USERNAME }} ${{ secrets.DOCKERHUB_TOKEN_RO }} milestones-api > milestones-api.log

      - name: Stop VPN connection
        if: always()
        run: |
          sudo chmod 444 vpn.log
          cat vpn.log
          sudo killall openvpn
