name: Deploy Docker Image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Whcih Docker image tag?'
        required: true
        default: 'latest'
      environment:
        description: 'To what environment?'
        type: choice
        default: 'development'
        options:
          - development
          - staging
          - production
      ref:
        description: 'Branch with correct secrets.txt file?'
        default: 'staging'
jobs:
  deploy:
    name: Deploy ${{ github.event.inputs.tag }} to ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      # the purpose of the checkout here is to obtain the secrets.txt file, which will come from the default branch
      # unless told otherwise
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.ref }}
          fetch-depth: 1

      - name: Copy secrets config file
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.AWS_HOST }}
          port: 22
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_KEY }}
          source: secrets.txt
          target: /home/ubuntu/config/

      - name: Prepare the .env file with secrets config file and Docker tag
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AWS_HOST }}
          port: 22
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_KEY }}
          script: |
            cd /home/ubuntu/config
            ./dotenv.py --token ${{ secrets.VAULT_TOKEN }} --filename secrets.txt --tag ${{ github.event.inputs.tag }}

      - name: Pull image and run Docker Compose
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AWS_HOST }}
          port: 22
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_KEY }}
          script: |
            cd /home/ubuntu/config
            ./run.sh ${{ secrets.DOCKERHUB_USERNAME }} ${{ secrets.DOCKERHUB_TOKEN }}
