name: Deploy Docker Image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag?'
        required: true
        default: 'latest'
      environment:
        description: 'Environment?'
        type: choice
        default: 'development'
        options:
          - development
          - staging
          - production
jobs:
  deploy:
    name: Deploy ${{ github.event.inputs.tag }} to ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    steps:

      - name: Pull image and run Docker Compose
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_KEY }}
          port: 22
          script: cd /home/ubuntu/config && ./run.sh ${{ secrets.DOCKERHUB_USERNAME }} ${{ secrets.DOCKERHUB_TOKEN }} ${{ github.event.inputs.tag }} 'no-token' 
