name: Lint Code

on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  lint-code:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo (current branch)
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Install dependencies
        run: |
          sudo apt-get install -y moreutils
          pip install --upgrade pip
          pip install ruff

      - name: Setup Github
        run: |
          # user.name/user.email comes from the last commit
          git config --global user.name "$(git log -n 1 --pretty=format:%an)"
          git config --global user.email  "$(git log -n 1 --pretty=format:%ae)"

      - name: Convert tabs to 4 spaces
        run: |
          find ./app -name "*.py" -type f -exec bash -c 'expand -t 4 "$0" | sponge "$0"' {} \;
          git add ./app
          git commit -a -m "Tabs to spaces" --allow-empty

      - name: Run Ruff and auto-fix common rules
        run: |
          # run through and auto-fix these simple rules
          declare -A RUFF_RULES=(
            ["F401"]="remove unused imports"
            ["UP039"]="parentheses after class definition"
            ["Q002"]="single quote docstring"
            ["E401"]="multiple imports on one line"
            ["F841"]="remove unused variables"
          )
          for RULE in "${!RUFF_RULES[@]}";
          do
            ruff check ./app --select ${RULE} --fix
            # only commit if there are changes, --allow-empty can probably be omitted
            RESULT=$(git diff-index HEAD -- | awk '{print $3}' | wc  -l)
            if [ ${RESULT} -ne "0" ]; then
              git add ./app
              git commit -a -m "${RUFF_RULES[${RULE}]}" --allow-empty
            fi
          done

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
