name: Postman Tests on PRs

on:
    pull_request:
       types: [opened, reopened]
    push:
        branches:
          - 'clark-pr-tests'
    
jobs:
  run-postman:
    name: Docker build and run Postman test suite
    runs-on: ubuntu-latest
    env:
        DD_API_KEY: "foobar"
        DD_APP_KEY: "foobar"
        ACCOUNT_SID: "foobar"
        ACCOUNT_TOKEN: "foobar"
        ALGORITHM: "HS256"
        AWS_ACCESS_KEY_ID: "foobar"
        AWS_SECRET_ACCESS_KEY: "foobar"
        SECRET_KEY: "foobar"
        SPARKPOST_KEY: "foobar"
        TWILIO_FROM: "+16193299600"
        
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Start Docker containers
        run: |
          docker-compose up --build --detach

      - name: Pause to let app to start
        run: |
          sleep 30

      - name: Run Postman tests
        run: |
          docker exec --tty milestones_api /app/tests/postman.sh

      - name: Stop Docker containers
        if: always()
        run: |
          docker-compose down

      - name: Test
        if: always()
        run: |
          echo "job status is ${{ job.status }}"

      - name: Update Github status
        if: always()
        uses: ouzi-dev/commit-status-updater@v2
        with:
          name: "Postman integration test results"
          status: ${{ job.status }}