---

    name: Trigger Build

    on:
      workflow_dispatch:
        inputs:
          ref:
            description: "From which branch?"
            default: "dev"
          level:
            description: "What build level?"
            type: choice
            default: "patch"
            options:
                - patch
                - minor
                - major
          environment:
            description: "Which environment?"
            type: environment

    jobs:
      empty-commit:
        name: Push Empty Commit
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4
            with:
              ref: ${{ github.head_ref }}
              fetch-depth: 0
              # persist-credentials: false # this must be false to use the PAT in the push below

          # - name: Checkout Blueboard's Shared GitHub Actions 🔧
          #   uses: actions/checkout@v4
          #   with:
          #     repository: blueboard/github_actions
          #     token: ${{ secrets.BLUEBOARD_BOT_PAT }}
          #     path: .github/actions

          - name: Make Empty Commit to Trigger Build
            run: |
              git config --global user.name '$(git log -n 1 --pretty=format:%an)'
              git config --global user.email  '$(git log -n 1 --pretty=format:%ae)'
              git commit --allow-empty -m "no-op ${{ inputs.level }}"
              git push --force-with-lease

          # - name: Make Empty Commit to Trigger Build
          #   uses: ./.github/actions/trigger-build
          #   with:
          #     token: ${{ secrets.BLUEBOARD_BOT_PAT }}
          #     level: ${{ inputs.level }}
          #     ref: ${{ inputs.ref }}
          #     repository: ${{ github.event.repository.name }}
